<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaFVOif\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaFVOif/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIaFVOif.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerIaFVOif\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerIaFVOif\srcProdProjectContainer(array(
    'container.build_hash' => 'IaFVOif',
    'container.build_id' => '31e7da8d',
    'container.build_time' => 1585168915,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaFVOif');
