<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.bUJ8MiH' shared service.

return $this->privates['service_locator.bUJ8MiH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('cache' => function () {
    return ($this->services['cache.app'] ?? $this->load('getCache_AppService.php'));
}, 'markdown' => function () {
    return ($this->services['markdown.parser'] ?? $this->services['markdown.parser'] = new \Knp\Bundle\MarkdownBundle\Parser\Preset\Light());
}));
