<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\MarkdownHelper' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/MarkdownHelper.php';

$a = new \Symfony\Bridge\Monolog\Logger('markdown');
$a->pushHandler(($this->privates['monolog.handler.console'] ?? $this->privates['monolog.handler.console'] = new \Symfony\Bridge\Monolog\Handler\ConsoleHandler(NULL, true, array())));
$a->pushHandler(($this->privates['monolog.handler.main'] ?? $this->getMonolog_Handler_MainService()));

return $this->privates['App\Service\MarkdownHelper'] = new \App\Service\MarkdownHelper(($this->services['cache.app'] ?? $this->load('getCache_AppService.php')), ($this->services['markdown.parser'] ?? $this->services['markdown.parser'] = new \Knp\Bundle\MarkdownBundle\Parser\Preset\Light()), $a);
