<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.FBC3YNh' shared service.

return $this->privates['service_locator.FBC3YNh'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('markdown' => function () {
    return ($this->services['markdown.parser'] ?? $this->services['markdown.parser'] = new \Knp\Bundle\MarkdownBundle\Parser\Preset\Light());
}, 'markdownHelper' => function (): ?\App\Service\MarkdownHelper {
    return ($this->privates['App\Service\MarkdownHelper'] ?? $this->load('getMarkdownHelperService.php'));
}));
