<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7M6xgaU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7M6xgaU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7M6xgaU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7M6xgaU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7M6xgaU\srcDevDebugProjectContainer(array(
    'container.build_hash' => '7M6xgaU',
    'container.build_id' => '27e3097b',
    'container.build_time' => 1585265366,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7M6xgaU');
